NewUrl.create(url:'http://www.google.es')
NewUrl.create(url:'http://www.facebook.com')
NewUrl.create(url:'http://www.spotify.es')
NewUrl.create(url:'http://www.msn.es')
NewUrl.create(url:'http://www.hotmail.es')
NewUrl.create(url:'http://www.ironhack.com')