# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 298efd19ef171f9bba43f4f80eabfa6c2ed2e0fd981355ee47fcf0b26000c5660d8394f2bef1713ac52d1aae48fd1e7530b0db305a32ccd4a60d69931dd83cd0

test:
  secret_key_base: 287cfa8742cf6ea7cc60e1dfc9a0e72714dfd888eb38a5bc0c2d4cf1305eb63b2894336756c7b40325169324fb6851a891c4b81fe49772934e988665a9bea60a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
