# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a7c6f6f68a0e9ea6923b6c2afe0815922fec4b3b65d4c9550cca1716a8a724ced14cb5ee04d1251ec7d5c60c765c14fa7fd7608a1bb9c97cdbabc0d0d162eab5

test:
  secret_key_base: 5c59db65d83c028feb46d9f810a0a653b75dcd49105a866d1dbfef046eced0fc708dcdb6d015778cbfd442fc019da36960c4847a2024bf9e21fc600ae49820c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
